from enum import Enum


class Tag(str, Enum):
    AUTHENTICATION = "AUTHENTICATION"
    USERS = "USERS"
    PRODUCTS = "PRODUCTS"
    CARTS = "CARTS"
    ORDERS = "ORDERS"

    REGRESSION = "REGRESSION"
    SMOKE = "SMOKE"

    GET_ENTITY = "GET_ENTITY"
    GET_ENTITIES = "GET_ENTITIES"
    CREATE_ENTITY = "CREATE_ENTITY"
    UPDATE_ENTITY = "UPDATE_ENTITY"
    DELETE_ENTITY = "DELETE_ENTITY"
